"""adding services and user_services tables

Revision ID: 04f83b62c550
Revises: 9ed219c840e4
Create Date: 2020-06-03 09:48:49.025427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f83b62c550'
down_revision = '9ed219c840e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_service_description'), 'service', ['description'], unique=False)
    op.create_table('user__service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user__service_end_date'), 'user__service', ['end_date'], unique=False)
    op.create_index(op.f('ix_user__service_start_date'), 'user__service', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user__service_start_date'), table_name='user__service')
    op.drop_index(op.f('ix_user__service_end_date'), table_name='user__service')
    op.drop_table('user__service')
    op.drop_index(op.f('ix_service_description'), table_name='service')
    op.drop_table('service')
    # ### end Alembic commands ###
